import { NextResponse } from "next/server";
import {
  BETTER_AUTH_SECRET,
  INTERNAL_API_TOKEN,
  VAULT_PART_1,
} from "@/lib/secrets";

/**
 * Nightly environment snapshot (generated by backup-job-04).
 * Consumed by the on-call engineer and the SSO service.
 */
export async function GET() {
  const body = [
    "# Acme Employee Portal — environment snapshot 2026-02-10 03:00 CET",
    "# TODO(M.Chen): rotate these before the audit, stop publishing this file",
    "",
    `BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}`,
    "BETTER_AUTH_URL=http://localhost:3000",
    `INTERNAL_API_TOKEN=${INTERNAL_API_TOKEN}`,
    `VAULT_CUSTODIAN_1=${VAULT_PART_1}`,
    "# custodian-2 lives with Security Operations (analytics workspace)",
    "# sso database: memory (resets on deploy)",
    "",
  ].join("\n");
  return new NextResponse(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}
